Profile Endpoints with TypeScript
InnovationDepartment/proxima.users.profile pull request #1
Opened 2022-02-01 01:47 UTC by FelixRamirezJr

2022-02-01 18:41 UTC, jeffgraham reviewed
these can be removed, there are an env var example from the examples.basicApi proj

https://github.com/InnovationDepartment/proxima.users.profile/blob/feature-init-two/src/config/index.ts#L23

https://github.com/InnovationDepartment/proxima.users.profile/blob/main/serverless.yml#L11

https://github.com/InnovationDepartment/proxima.users.profile/blob/main/serverless.yml#L55

2022-02-01 19:27 UTC, jeffgraham requested changes

2022-02-01 19:27 UTC, jeffgraham commented on src/test/unit/handlers/updateProfile.test.ts
> +          'proxima.users.profile': entitlements
does this test setup need the same typing as getProfile.test.ts ?

2022-02-01 19:27 UTC, jeffgraham commented on src/types/models/user.ts
> +  userId?: User['userId']
should userId be required?

2022-02-01 19:30 UTC, jeffgraham reviewed
this can be removed if we use `sls offline -s=develop --noAuth | pino-pretty`

https://github.com/InnovationDepartment/proxima.users.profile/blob/feature-init-two/serverless.yml#L14

2022-02-01 21:16 UTC, FelixRamirezJr commented on package.json
>      "dev": "sls offline -s=develop --noAuth | pino-pretty",
Yeah we can remove for now

2022-02-01 21:19 UTC, FelixRamirezJr commented on src/test/e2e/env/feature-init-two.postman_environment.json
> +  "name": "proxima-users-profile",
ok sounds good

2022-02-01 22:34 UTC, FelixRamirezJr commented on src/test/unit/handlers/updateProfile.test.ts
> +          'proxima.users.profile': entitlements
Correct, I have updated this so both tests can get the event JSON from a `mocks/event.js` file. There was some repetitiveness that I thought we could get rid of. Take a look at those changes and let me know if you have any questions or suggestions. 

https://github.com/InnovationDepartment/proxima.users.profile/pull/1/commits/2076e72e0d7d729b83c7a8026250d354e45f9d3a

2022-02-01 22:44 UTC, FelixRamirezJr commented on src/types/models/user.ts
I actually got rid of this. Since we only have a `GetProfileResponse` and an `UpdateUserResponse`, there is no need to have a `GenericLambdaResponse`. I think you are right though, if there is a larger project where we are using a Generic__Response, it will be better to have clear naming to know what layer it belongs to.

2022-02-01 23:00 UTC, FelixRamirezJr commented on src/types/models/user.ts
> +export type GetUserResults = {
Hmm not sure what you mean by: `seems more comment`

But I think you are saying that Result is better than Results, which I agree. I have made that update, let me know if I misunderstood your suggestion.

2022-02-01 23:02 UTC, FelixRamirezJr commented on src/types/models/user.ts
> +  statusCode: GenericLambdaResponse['statusCode']
I got rid of the `GenericLambdaResponse` a few commits ago and this was updated to use number 👍 
 
Essentially I was envisioning we could use the `GenericLambdaResponse` in a few places. But ended up removing it since we don't need that extra layer of abstraction on such a simple project.

2022-02-01 23:09 UTC, FelixRamirezJr commented on src/types/models/user.ts
> +  userId?: User['userId']
Correct! Thanks for catching this -- updated this now

2022-02-02 21:34 UTC, jeffgraham commented on src/types/models/user.ts
> +  statusCode: GenericLambdaResponse['statusCode']
👍

2022-02-02 21:38 UTC, jeffgraham approved these changes

2022-02-02 21:38 UTC, jeffgraham commented on serverless.yml
>    serverless-offline:
last issue, i think we can remove these since we're setting them in the `sls offline` command

2022-02-02 21:47 UTC, FelixRamirezJr commented on serverless.yml
>    serverless-offline:
Ok, just removed them!

2022-02-02 23:17 UTC, merged